-- 005: missing columns

ALTER TABLE pool_members ADD COLUMN IF NOT EXISTS id SERIAL;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS approved_by INT;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;
ALTER TABLE sla_rules ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE saved_searches ADD COLUMN IF NOT EXISTS last_result_count INT DEFAULT 0;
ALTER TABLE saved_searches ADD COLUMN IF NOT EXISTS last_checked_at TIMESTAMPTZ;
