#!/usr/bin/env bash
# ============================================================================
# PULSE — interactive setup
# Prompts for the 4 values engineer needs to configure, writes .env, boots.
# Usage:  ./setup.sh
# ============================================================================
set -e

cd "$(dirname "$0")"

C_RESET='\033[0m'; C_BOLD='\033[1m'; C_CYAN='\033[36m'; C_GREEN='\033[32m'; C_YELLOW='\033[33m'; C_RED='\033[31m'

echo -e "${C_BOLD}${C_CYAN}"
echo "============================================================"
echo " PULSE — first-time setup"
echo "============================================================"
echo -e "${C_RESET}"

# ---------------------------------------------------------------------------
# Detect existing .env
# ---------------------------------------------------------------------------
if [ -f .env ]; then
    echo -e "${C_YELLOW}.env already exists.${C_RESET}"
    read -r -p "Overwrite? [y/N]: " ans
    case "$ans" in
        y|Y|yes|YES) cp .env ".env.bak.$(date +%Y%m%d_%H%M%S)"; echo "  backed up to .env.bak.*";;
        *) echo "Aborting. Edit .env manually or remove it first."; exit 0;;
    esac
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
prompt() {
    # $1=label  $2=default  $3=varname  $4=secret(y/n)
    local label="$1" default="$2" var="$3" secret="${4:-n}" val=""
    if [ -n "$default" ]; then
        if [ "$secret" = "y" ]; then
            read -r -s -p "$(echo -e "${C_BOLD}${label}${C_RESET} [hidden, default=${default}]: ")" val; echo
        else
            read -r -p "$(echo -e "${C_BOLD}${label}${C_RESET} [${default}]: ")" val
        fi
        val="${val:-$default}"
    else
        if [ "$secret" = "y" ]; then
            read -r -s -p "$(echo -e "${C_BOLD}${label}${C_RESET} (hidden): ")" val; echo
        else
            read -r -p "$(echo -e "${C_BOLD}${label}${C_RESET}: ")" val
        fi
    fi
    eval "$var=\"\$val\""
}

# ---------------------------------------------------------------------------
# Collect 4 settings
# ---------------------------------------------------------------------------
echo -e "${C_CYAN}1) OpenRouter API key${C_RESET} — enables AI features (chat, vision OCR, summary, matching)."
echo "   Get one at https://openrouter.ai/keys  ·  Leave blank to skip (AI features disabled)."
prompt "OPENROUTER_API_KEY" "" OPENROUTER_API_KEY y
echo

echo -e "${C_CYAN}2) Superadmin login${C_RESET}"
prompt "Admin ID (username)" "pulse_admin" SUPERADMIN_ID n
prompt "Admin password" "admin" SUPERADMIN_PASS y
echo

echo -e "${C_CYAN}3) HTTP port${C_RESET} — port your browser connects to."
prompt "Port" "8090" PORT n
echo

# ---------------------------------------------------------------------------
# Auto-generated secrets
# ---------------------------------------------------------------------------
DB_PASS_AUTO="$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 32)"
JWT_SECRET_AUTO="$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -d '/+=' | head -c 64)"

# ---------------------------------------------------------------------------
# Write .env
# ---------------------------------------------------------------------------
cat > .env <<EOF
# Generated by setup.sh on $(date -Iseconds)
# Re-run ./setup.sh to regenerate. Manual edits are preserved next time
# only if you cancel the overwrite prompt.

# --- HTTP ---
PORT=${PORT}

# --- AI (OpenRouter) ---
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}

# --- Superadmin ---
SUPERADMIN_ID=${SUPERADMIN_ID}
SUPERADMIN_PASS=${SUPERADMIN_PASS}
# (SUPERADMIN_PASS is bcrypt-hashed at boot. For prod, replace with
#  SUPERADMIN_PASS_HASH=\$(docker run --rm python:3.11-slim python -c \\
#  "import bcrypt; print(bcrypt.hashpw(b'YourPass', bcrypt.gensalt(12)).decode())") )

# --- Database ---
DB_USER=pulse
DB_PASS=${DB_PASS_AUTO}
DB_DATABASE=pulsedb

# --- Auth / Sessions ---
JWT_SECRET=${JWT_SECRET_AUTO}
JWT_EXPIRY_H=8

# --- Runtime ---
DEV_MODE=false
WORKERS=1
OCR_CONCURRENCY=1
RATE_LIMIT=600/minute

# --- Origins (auto-allow any same-host by default) ---
ALLOWED_ORIGIN_REGEX=^https?://[^/]+$

# --- Redis ---
REDIS_URL=redis://redis:6379/0
EOF

chmod 600 .env
echo -e "${C_GREEN}✓ .env written${C_RESET}"
echo

# ---------------------------------------------------------------------------
# Build + boot
# ---------------------------------------------------------------------------
read -r -p "Build + start containers now? [Y/n]: " ans
case "$ans" in
    n|N|no|NO) echo "Skipping. Run: docker compose up -d --build"; exit 0;;
esac

echo -e "${C_CYAN}Building (5–15 min on first run)…${C_RESET}"
docker compose build api

echo -e "${C_CYAN}Booting…${C_RESET}"
docker compose up -d

# ---------------------------------------------------------------------------
# Wait for health
# ---------------------------------------------------------------------------
echo -n "Waiting for API to become healthy"
ATTEMPTS=0
until curl -sf "http://localhost:${PORT}/api/health" >/dev/null 2>&1; do
    ATTEMPTS=$((ATTEMPTS + 1))
    if [ "$ATTEMPTS" -ge 60 ]; then
        echo
        echo -e "${C_RED}Timed out. Check logs:${C_RESET}  docker logs pulse-api --tail 80"
        exit 1
    fi
    echo -n "."
    sleep 3
done
echo " ready."

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo
echo -e "${C_GREEN}${C_BOLD}============================================================${C_RESET}"
echo -e "${C_GREEN}${C_BOLD} PULSE is running${C_RESET}"
echo -e "${C_GREEN}${C_BOLD}============================================================${C_RESET}"
echo
echo "  URL:      http://localhost:${PORT}"
echo "  Login:    ${SUPERADMIN_ID} / ${SUPERADMIN_PASS}"
echo
echo "  Health:   curl http://localhost:${PORT}/api/health"
echo "  Logs:     docker logs -f pulse-api"
echo "  Stop:     docker compose down"
echo "  Reset:    docker compose down -v   (destructive — wipes DB)"
echo
if [ -z "$OPENROUTER_API_KEY" ]; then
    echo -e "${C_YELLOW}NOTE: AI features disabled (no OPENROUTER_API_KEY). Re-run ./setup.sh to add one.${C_RESET}"
fi
